spring:
  application:
    name: mdm_employee
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://mdm1.ywztmdm-mysql-mdm:3306/mdm_employee?characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123@mdm.CN
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    mysql-hr:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.255.21.221:3306/hr_db_prd?characterEncoding=utf8&allowMultiQueries=true
      username: ywztmdm
      password: UX#2cb57
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    mysql-hr-file:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.255.21.221:3306/hr_file?characterEncoding=utf8&allowMultiQueries=true
      username: zhongtai_r
      password: 23#2u2xN
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "3MB"
      max-file-size: "2MB"

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IPADDRESS}
  client:
    serviceUrl:
      defaultZone: http://10.255.21.146:8761/eureka/,http://10.255.21.147:8761/eureka,http://10.255.21.148:8761/eureka

#日志插件默认配置
gwmlog:
  #平台名称，必须全小写，不可以有特殊字符，请使用部门名称简写（如：ywztb）
  platformname: "ywztb"
  #项目名称，必须全小写，不可以有特殊字符（如：mes）
  projectname: domain-hr
  default:
    #默认索引名称，必须全小写，不可以有特殊字符
    indexname: "mdm"
    #默认日志类型，必须全小写，不可以有特殊字符（如：info、debug、warn、exception、error）
    logtype: "mdm_employee"


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  sql-hr-server: classpath:/mapper-hr/*Mapper.xml
  sql-hr-file-server: classpath:/mapper-hr-file/*Mapper.xml
  mybatis-locations: classpath:/mybatis/mybatisConfig.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
    #打印sql信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#暴露全部的监控信息
management:
  #公开所有端点 指定公开部分端点
  endpoints:
    web:
      exposure:
        include: "health,info"
      #跨域访问配置
  #      cors:
  #        allowed-origins: ""
  #        allowed-methods: "get","post"
  #单个端点操作
  endpoint:
    health:
      show-details: ALWAYS
  #暴漏端点端口号 与服务端口号不冲突
#  server:
#    port: 9091


oss:
  minio:
    userName: wuningfei
    paasword: 123@123.com
    host: a674a9b8dcaacbcf.test.paas.gwm.cn
    uri: /api/v1/share
    bucketName: hrbucket
    expiry: 604800